'use client';
import { useRouter } from 'next/navigation';
import './globals.css';
import Link from 'next/link';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const router = useRouter();

  const onClickUrl = (url: string) => {
    router.push(url);
  };
  return (
    <html lang="en">
      <body>
        <div>Header Navbar</div>
        <ul>
          {/*  navigasi menggunakan next link */}
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link href="/dashboard">Dashboard</Link>
          </li>
          <li style={{cursor:"pointer"}} onClick={() => onClickUrl('/settings')}>
            {/* Menggunakan router push */}
            Settings
          </li>
        </ul>
        {children}
        <div>Footer</div>
      </body>
    </html>
  );
}
