import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div>Header Navbar</div>
        {children}
        <div>Footer</div>
      </body>
    </html>
  );
}
